// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_all_sets.sql

package database

import (
	"context"
)

const getAllSets = `-- name: GetAllSets :many
SELECT
    code, name, created_at, updated_at
FROM
    sets
ORDER BY name ASC
`

func (q *Queries) GetAllSets(ctx context.Context) ([]Set, error) {
	rows, err := q.db.Query(ctx, getAllSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Set
	for rows.Next() {
		var i Set
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
