// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID               uuid.UUID
	ScryfallOracleID uuid.UUID
	Name             string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Set struct {
	Code      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SetCard struct {
	ID          uuid.UUID
	ScryfallID  uuid.UUID
	MtgjsonUuid uuid.UUID
	MtgjsonV4ID uuid.UUID
	SetCode     string
	CardID      uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
