// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForInsertCards implements pgx.CopyFromSource.
type iteratorForInsertCards struct {
	rows                 []InsertCardsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertCards) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertCards) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ScryfallID,
		r.rows[0].SetID,
		r.rows[0].Name,
		r.rows[0].CollectorNumber,
		r.rows[0].ColorIdentity,
		r.rows[0].Colors,
		r.rows[0].LanguageCode,
		r.rows[0].SpanishName,
		r.rows[0].Rarity,
		r.rows[0].TypeLine,
		r.rows[0].ScryfallApiUri,
		r.rows[0].ScryfallWebUri,
		r.rows[0].ScryfallOracleID,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForInsertCards) Err() error {
	return nil
}

func (q *Queries) InsertCards(ctx context.Context, arg []InsertCardsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"cards"}, []string{"scryfall_id", "set_id", "name", "collector_number", "color_identity", "colors", "language_code", "spanish_name", "rarity", "type_line", "scryfall_api_uri", "scryfall_web_uri", "scryfall_oracle_id", "created_at", "updated_at"}, &iteratorForInsertCards{rows: arg})
}

// iteratorForInsertSets implements pgx.CopyFromSource.
type iteratorForInsertSets struct {
	rows                 []InsertSetsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertSets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertSets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ScryfallID,
		r.rows[0].Code,
		r.rows[0].Name,
		r.rows[0].CreatedAt,
		r.rows[0].UpdatedAt,
	}, nil
}

func (r iteratorForInsertSets) Err() error {
	return nil
}

func (q *Queries) InsertSets(ctx context.Context, arg []InsertSetsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"sets"}, []string{"scryfall_id", "code", "name", "created_at", "updated_at"}, &iteratorForInsertSets{rows: arg})
}
