// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_sets.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertSetsParams struct {
	ScryfallID pgtype.UUID
	Code       string
	Name       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
