// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_cards.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertCardsParams struct {
	ScryfallID       pgtype.UUID
	SetID            pgtype.UUID
	Name             string
	CollectorNumber  string
	ColorIdentity    pgtype.Text
	Colors           pgtype.Text
	LanguageCode     string
	SpanishName      pgtype.Text
	Rarity           pgtype.Text
	TypeLine         string
	ScryfallApiUri   string
	ScryfallWebUri   string
	ScryfallOracleID pgtype.UUID
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}
