// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: insert_cards.sql

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InsertCardsParams struct {
	ID               pgtype.UUID
	Name             string
	ScryfallOracleID pgtype.UUID
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}
