// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ScryfallID       pgtype.UUID
	SetID            pgtype.UUID
	Name             string
	CollectorNumber  string
	ColorIdentity    pgtype.Text
	Colors           pgtype.Text
	LanguageCode     string
	SpanishName      pgtype.Text
	Rarity           pgtype.Text
	TypeLine         pgtype.Text
	ScryfallApiUri   string
	ScryfallWebUri   string
	ScryfallOracleID pgtype.UUID
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Set struct {
	ScryfallID pgtype.UUID
	Code       string
	Name       string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
