// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Card struct {
	ID               pgtype.UUID
	ScryfallOracleID pgtype.UUID
	Name             string
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
}

type Set struct {
	Code      string
	Name      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type SetCard struct {
	ID          pgtype.UUID
	ScryfallID  pgtype.UUID
	MtgjsonUuid pgtype.UUID
	MtgjsonV4ID pgtype.UUID
	SetCode     string
	CardID      pgtype.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
