// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_set.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateSet = `-- name: UpdateSet :exec
UPDATE sets
SET  code = $2,
    name = $3,
    updated_at = $4
WHERE scryfall_id = $1
`

type UpdateSetParams struct {
	ScryfallID pgtype.UUID
	Code       string
	Name       string
	UpdatedAt  pgtype.Timestamp
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) error {
	_, err := q.db.Exec(ctx, updateSet,
		arg.ScryfallID,
		arg.Code,
		arg.Name,
		arg.UpdatedAt,
	)
	return err
}
