// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_set.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateSet = `-- name: UpdateSet :exec
UPDATE sets
SET name = $2,
    updated_at = $3
WHERE code = $1
`

type UpdateSetParams struct {
	Code      string
	Name      string
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) UpdateSet(ctx context.Context, arg UpdateSetParams) error {
	_, err := q.db.Exec(ctx, updateSet, arg.Code, arg.Name, arg.UpdatedAt)
	return err
}
