// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_card.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET set_id = $2,
    name = $3,
    collector_number = $4,
    color_identity = $5,
    colors = $6,
    language_code = $7,
    spanish_name = $8,
    rarity = $9,
    type_line = $10,
    scryfall_api_uri = $11,
    scryfall_web_uri = $12,
    scryfall_oracle_id = $13,
    updated_at = $14
WHERE scryfall_id = $1
`

type UpdateCardParams struct {
	ScryfallID       pgtype.UUID
	SetID            pgtype.UUID
	Name             string
	CollectorNumber  string
	ColorIdentity    pgtype.Text
	Colors           pgtype.Text
	LanguageCode     string
	SpanishName      pgtype.Text
	Rarity           pgtype.Text
	TypeLine         pgtype.Text
	ScryfallApiUri   string
	ScryfallWebUri   string
	ScryfallOracleID pgtype.UUID
	UpdatedAt        pgtype.Timestamp
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.ScryfallID,
		arg.SetID,
		arg.Name,
		arg.CollectorNumber,
		arg.ColorIdentity,
		arg.Colors,
		arg.LanguageCode,
		arg.SpanishName,
		arg.Rarity,
		arg.TypeLine,
		arg.ScryfallApiUri,
		arg.ScryfallWebUri,
		arg.ScryfallOracleID,
		arg.UpdatedAt,
	)
	return err
}
