// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_card.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET scryfall_oracle_id = $2,
    name = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateCardParams struct {
	ID               pgtype.UUID
	ScryfallOracleID pgtype.UUID
	Name             string
	UpdatedAt        pgtype.Timestamp
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.ID,
		arg.ScryfallOracleID,
		arg.Name,
		arg.UpdatedAt,
	)
	return err
}
