name: db

on:
  pull_request:
    branches: [main]

jobs:
  goose:
    name: Goose Migration
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Goose Up Migration
        run: goose postgres "$DB_URL" up
        working-directory: sql/schema
        env:
          DB_URL: "postgres://postgres:postgres@localhost:5432/postgres"

      - name: Goose Down Migration
        run: goose postgres "$DB_URL" down
        working-directory: sql/schema
        env:
          DB_URL: "postgres://postgres:postgres@localhost:5432/postgres"
