#!/bin/bash

# Validate goose migrations
(
    cd sql/schema || exit 1
    goose validate || exit 1
)

# Validate go formatting
test -z "$(go fmt ./...)" || exit 1

# go static analysis
staticcheck ./... || exit 1

# go security analysis
gosec ./... || exit 1
